version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mosb
      - POSTGRES_USER=mosb
      - POSTGRES_PASSWORD=Passw0rd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5